# Generated by Django 5.0.1 on 2024-01-30 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MontUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=25, verbose_name='User Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('dorm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('condition', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateField(verbose_name='Date Posted')),
                ('date_updated', models.DateField(verbose_name='Date Updated')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.montuser')),
            ],
        ),
    ]
