# Generated by Django 5.0.1 on 2024-02-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_date_updated_alter_listing_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, default='static/listings/default_image.jpeg', null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='montuser',
            name='dorm',
            field=models.CharField(choices=[('page', 'Page'), ('emerson', 'Emerson'), ('clark', 'Clark'), ('vk', 'VK'), ('armington', 'Armington'), ('glc', 'GLC'), ('off campus', 'Off Campus')], max_length=50),
        ),
    ]
