# Generated by Django 5.0.1 on 2024-02-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_photo_alter_montuser_dorm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_created',
        ),
    ]
