# Generated by Django 5.0.1 on 2024-02-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('dorm_related', 'Dorm Related'), ('clothing_accessories', 'Clothing and Accessories'), ('sports_outdoors', 'Sports and Outdoors'), ('westmont_textbooks', 'Westmont Textbooks'), ('other_books', 'Other Books'), ('music', 'Music'), ('automotive', 'Automotive'), ('other', 'Other')], max_length=50),
        ),
    ]
