# Generated by Django 5.0.1 on 2024-02-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montuser',
            name='email',
            field=models.EmailField(default='b@b.com', max_length=254, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='montuser',
            name='first_name',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='montuser',
            name='last_name',
            field=models.CharField(default='b', max_length=60),
        ),
        migrations.AlterField(
            model_name='montuser',
            name='phone',
            field=models.CharField(default=0, max_length=25, verbose_name='User Phone'),
        ),
    ]
