# Generated by Django 5.0.1 on 2024-03-17 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_created_at_listing_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montuser',
            name='dorm',
        ),
        migrations.RemoveField(
            model_name='montuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='montuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='montuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='montuser',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='montuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
