# Generated by Django 5.0.1 on 2024-04-24 19:13

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_remove_montuser_dorm_remove_montuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=listings.models.MediaStorage(), upload_to='listings/'),
        ),
    ]
